# Generated by Django 4.2 on 2023-08-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=6, verbose_name='Placa')),
                ('marca', models.CharField(max_length=20, verbose_name='Marca')),
            ],
        ),
    ]
