# Generated by Django 4.2 on 2023-08-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.IntegerField(max_length=15, verbose_name='Número Documento')),
                ('nombre', models.CharField(max_length=35, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=35, verbose_name='Apellido')),
            ],
        ),
    ]
