# Generated by Django 4.2 on 2023-09-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_delete_usuarios_ficha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.PositiveIntegerField(verbose_name='Nombre')),
                ('telefono', models.DateField(verbose_name='Teléfono')),
            ],
            options={
                'verbose_name_plural': 'Arls',
            },
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='correo_ins',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='correo_personal',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ficha',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='primer_apellido',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='primer_nombre',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='segundo_apellido',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='segundo_nombre',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefono_contacto',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefono_personal',
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(default='Apellidos', max_length=45, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(default='lubricentro@gmail.com', max_length=50, verbose_name='Correo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default='Nombres', max_length=45, verbose_name='Nombres'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.PositiveIntegerField(default='3149675543', verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('A', 'Administrador'), ('S', 'Secretaria')], max_length=2, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería')], max_length=2, verbose_name='Tipo de Documento'),
        ),
        migrations.DeleteModel(
            name='Ficha',
        ),
    ]
