# Generated by Django 4.2 on 2023-09-19 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_arl_remove_usuario_correo_ins_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arl',
            name='nombre',
            field=models.CharField(max_length=15, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='arl',
            name='telefono',
            field=models.IntegerField(verbose_name='Teléfono'),
        ),
    ]
