# Generated by Django 4.2 on 2023-10-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_arl_nombre_alter_arl_telefono'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Arl',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(default='cra3 #4-5', max_length=15, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipoUsuario',
            field=models.CharField(choices=[('A', 'Administrador'), ('S', 'Secretaria')], default='Administrador', max_length=2, verbose_name='tipoUsuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula'), ('NIT', 'NIT'), ('CE', 'Cédula de Extranjería')], max_length=20, verbose_name='Tipo de Documento'),
        ),
        migrations.DeleteModel(
            name='Integrantes',
        ),
        migrations.DeleteModel(
            name='Proyecto',
        ),
    ]
