# Generated by Django 4.2 on 2023-09-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=45, verbose_name='Nombre Producto')),
                ('descripcion', models.CharField(max_length=45, verbose_name='Descripcion')),
                ('categoria', models.CharField(choices=[('ACCESORIOS', 'Accesorios'), ('RESPUESTOS', 'Repuestos'), ('CONSUMIBLES', 'Consumibles')], max_length=11, verbose_name='Categoria')),
                ('precio', models.IntegerField(max_length=15, verbose_name='precio')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
            ],
        ),
    ]
